# Generated by Django 4.1 on 2022-08-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='')),
                ('price_default', models.IntegerField()),
                ('price_now', models.IntegerField()),
                ('buy_status', models.BooleanField(default=False)),
            ],
        ),
    ]
