# Generated by Django 4.1 on 2022-09-01 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comics',
            options={'verbose_name_plural': 'Comics'},
        ),
        migrations.AlterField(
            model_name='comics',
            name='price_default',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='comics',
            name='price_now',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='comics',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.publishers'),
        ),
    ]
