# Generated by Django 4.1 on 2022-09-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comics_time_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
