# Generated by Django 4.1 on 2022-09-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comics_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='quantity_purchased',
            field=models.IntegerField(default=0),
        ),
    ]
