# Generated by Django 4.1 on 2022-09-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comics_quantity_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comics',
            name='in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comics',
            name='quantity_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comics',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
