# Generated by Django 4.1 on 2023-03-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comics_height_comics_in_stock_comics_quantity_pages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comics_create_json',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=255)),
                ('description', models.TextField(default='description')),
                ('publisher', models.CharField(default=None, max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('quantity_pages', models.IntegerField(default=0)),
                ('pereplet', models.CharField(default=None, max_length=255)),
                ('age_rating', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('characters', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
