# Generated by Django 4.1 on 2023-03-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_comics_create_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics_create_json',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
