# Generated by Django 4.1 on 2023-03-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_comics_create_json_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics_create_json',
            name='buy_status',
            field=models.BooleanField(default=False),
        ),
    ]
